# Generated by Django 6.0.3 on 2026-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0006_alter_doctorprofile_level_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='اسم الإعداد (مثال: GEMINI_API_KEY)', max_length=50, unique=True)),
                ('value', models.TextField(help_text='قيمة الإعداد (المفتاح السري)')),
                ('description', models.CharField(blank=True, help_text='وصف الإعداد', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
