# Generated by Django 6.0.3 on 2026-03-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0008_alter_chatmessage_timestamp_aichatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(max_length=500, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='صورة الإعلان')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='رابط خارجي (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إعلان متحرك',
                'verbose_name_plural': 'الإعلانات المتحركة',
            },
        ),
    ]
