# Generated by Django 6.0.3 on 2026-03-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0009_adbanner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('doctor', 'governorate', 'street_name'), name='unique_branch_per_doctor'),
        ),
    ]
