# Generated by Django 6.0.3 on 2026-03-12 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0010_branch_unique_branch_per_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(help_text='اسم الإعداد (مثال: MAINTENANCE_MODE)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(help_text='قيمة الإعداد'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier (MAC or Unique ID)', max_length=255)),
                ('device_name', models.CharField(help_text='Human readable device name', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary device for notifications?')),
                ('is_verified', models.BooleanField(default=True, help_text='Is the device verified?')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-last_login'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
