# Generated by Django 6.0.3 on 2026-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0011_alter_systemsetting_key_alter_systemsetting_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Verification code sent to primary device', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
